### ISSUE TITLE
Log errors when PIE

### ISSUE THREAD

**Issue by imtrobin** [SkylakeOfficial/CrystalNodes#2]
Hi, in some projects, the  output log will  be flooded with errors when PIE

![image](https://github.com/SkylakeOfficial/CrystalNodes/assets/531606/6054b5f0-3561-4555-8e11-a7f6d3e39658)

**Comment by SkylakeOfficial** [comment]
It has been already fixed in the latest commit 82572b31c81891e5765576b79262240dd3b8a58d , but it hasn't been built to a  release yet.
