### ISSUE TITLE
Unreal Engine 5.5 upgrade

### ISSUE THREAD

**Issue by killgamesh1** [SkylakeOfficial/CrystalNodes#5]
Hello,
could you upgrade the plugin version to support unreal engine 5.5? I ask because it doesn't let me compile the project if I put the plugin as it is now to my unreal engine 5.5 project.

Thank you very much :)

**Comment by SkylakeOfficial** [comment]
Of course! I had the file ready before 5.5 release and forgot to submit it to Fab. Sorry to have kept you waiting.
